# numpy

In [1]:
import numpy as np

# Array fundemental

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a[0]

1

In [5]:
a[0] = 10 
a[0]

10

In [6]:
a[:3]

array([10,  2,  3])

In [8]:
b = a [3:]
b

array([4, 5])

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[1, 3]


8

In [11]:
a.ndim

2

In [12]:
a.shape

(3, 4)

In [13]:
a.size

12

In [14]:
a.dtype

dtype('int32')

# How to create a basic array

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.empty(4)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.33252325e-311])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [25]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
x = np.ones(2,dtype=np.int32)

# Adding, removing, and sorting elements

In [32]:
arr  = np.array([1,3,5,7,9,2,4,6,8])
print(arr)
np.sort(arr)



[1 3 5 7 9 2 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [34]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [36]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [37]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])


In [38]:
array_example.shape

(3, 2, 4)

In [39]:
array_example.ndim

3

In [40]:
array_example.size

24

# Can you reshape an array?

In [41]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [42]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [44]:

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [47]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [48]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [49]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [54]:
b = np.expand_dims(a, axis=1
)
b.shape

(6, 1)

In [55]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and slicing

In [56]:
data = np.array([1,2,3])

In [57]:
data[1]

2

In [61]:
data[0:2]

array([1, 2])

In [62]:
data[1:]

array([2, 3])

In [63]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
print(a[a<5])

[1 2 3 4]


In [66]:
a.shape

(3, 3)

In [67]:
divisable_by_2 = a[a % 2 ==0]
divisable_by_2

array([2, 4, 6, 8])

In [72]:
c = a[(a>2) & (a<11)]
print(c)

[3 4 5 6 7 8 9]


In [73]:
five_up = (a >= 5)
five_up

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [74]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))


# How to create an array from existing data

In [80]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [85]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [86]:
np.vstack((a1 , a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [87]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [88]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [90]:
np.hsplit(x , 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [92]:
np.vsplit(x , 1)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [93]:
np.hsplit(x , (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

# Basic array operations

In [95]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data + (ones)

array([2, 3])

In [96]:
data - ones

array([0, 1])

In [97]:
data  * data 

array([1, 4])

In [98]:
data / data

array([1., 1.])

In [99]:
a = np.array([1,2,3,4])
a.sum()

10

In [101]:
b = np.array([[1,1],[2,3]])
b.sum(axis=0)

array([3, 4])

In [102]:
b.sum(axis=1)

array([2, 5])

# Broadcasting

In [103]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [104]:
data = np.array([1,2,3])

data.max()

3

In [105]:
data.min()

1

In [106]:
data.mean()

2.0

In [107]:
data.sum()

6

In [108]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [109]:
print(a.sum())
print(a.mean())
print(a.max())

4.8595784
0.4049648666666667
0.82485143


In [111]:
print(a.max(axis = 0))

[0.54627315 0.82485143 0.40067661 0.56917101]


# Creating matrices

In [112]:
data = np.array([[1,2],
                 [3,4],
                 [5,6]])

data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
data[0,1]

2

In [116]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [118]:
data[0:2,0]

array([1, 3])

In [119]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [125]:
h =data.max(axis=0) , data.max(axis=1)
h

(array([5, 6]), array([2, 5, 6]))

In [127]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1,1])

data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [129]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [132]:
rng = np.random.default_rng()
rng.random(3)

array([0.03816331, 0.47881672, 0.4444641 ])

In [134]:
np.random.rand(3,4)

array([[0.25850587, 0.07407085, 0.40821321, 0.80105471],
       [0.08556691, 0.0534499 , 0.25714538, 0.48791945],
       [0.4433009 , 0.47251806, 0.42901923, 0.63737516]])

In [137]:
np.random.randint(5)

4

# Generating random numbers

In [138]:
rng.integers(5, size=(2, 4))

array([[1, 2, 3, 0],
       [1, 2, 4, 3]], dtype=int64)

# How to get unique items and counts

In [139]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [140]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [141]:
unique_values , indecis = np.unique(a , return_index=True)
print(indecis)

[ 0  2  3  4  5  6  7 12 13 14]


In [143]:
unique_values , occurence_count = np.unique(a , return_counts=True)
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


# Transposing and reshaping a matrix

In [144]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [150]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [151]:
arr = np.array([1,2,4,5,6])
reversed_arr = np.flip(arr)
reversed_arr

array([6, 5, 4, 2, 1])

In [152]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [153]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [154]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [155]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [156]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [157]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [159]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [160]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [161]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [162]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
